import i18n from '@/i18n'
import { render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { setDefaultHostServices } from '@cpa/plugin-ui'
import type { Project } from '@cpa/plugin-api'
import { EnvironmentPicker } from './EnvironmentPicker.js'

const SAMPLE_TOML = `# THIS IS AUTOGENERATED. DO NOT EDIT MANUALLY
version = 1
name = "MyEnv"

[setup]
script = "npm install"
`

const EMPTY_PROJECTS: readonly Project[] = Object.freeze([])

let openedSettingsSection: string | undefined
let openedSettingsParams: any = undefined
let mockUiService: any
let mockServices: any

beforeEach(async () => {
    await i18n.changeLanguage('en')
    openedSettingsSection = undefined
    openedSettingsParams = undefined
    mockUiService = {
        openSettings: vi.fn((section?: string, params?: any) => {
            openedSettingsSection = section
            openedSettingsParams = params
        }),
        pushToast: vi.fn(),
    }
    mockServices = {
        ui: mockUiService,
        projects: {
            getSnapshot: () => EMPTY_PROJECTS,
            subscribe: () => () => {},
        },
    }
    setDefaultHostServices(mockServices)
})

describe('EnvironmentPicker', () => {
    it('renders no environment chip and toggles environment menu', async () => {
        const user = userEvent.setup()
        render(<EnvironmentPicker />)

        const button = screen.getByRole('button', { name: /Environment/i })
        expect(button).toBeInTheDocument()
        expect(button).toHaveTextContent('No environment')
        expect(screen.queryByRole('menu')).not.toBeInTheDocument()

        // Open menu
        await user.click(button)
        expect(screen.getByRole('menu')).toBeInTheDocument()
        expect(screen.getByText('Environment')).toBeInTheDocument()
        expect(
            screen.getByRole('menuitem', { name: /Work without environment/i }),
        ).toBeInTheDocument()
        expect(
            screen.getByRole('menuitem', { name: /Set up project/i }),
        ).toBeInTheDocument()

        // Close on second click
        await user.click(button)
        expect(screen.queryByRole('menu')).not.toBeInTheDocument()
    })

    it('selects work without environment and triggers onChange', async () => {
        const user = userEvent.setup()
        const onChange = vi.fn()
        render(<EnvironmentPicker onChange={onChange} />)

        await user.click(screen.getByRole('button', { name: /Environment/i }))
        await user.click(screen.getByRole('menuitem', { name: /Work without environment/i }))

        expect(onChange).toHaveBeenCalledWith(null)
        expect(screen.queryByRole('menu')).not.toBeInTheDocument()
    })

    it('opens environments section in settings on clicking setup project with project target', async () => {
        const user = userEvent.setup()
        const mockProjects: Project[] = [
            {
                id: 'proj-1',
                name: 'Backend API Project',
                path: '/workspaces/backend-api',
                pinned: false,
                createdAt: 1000,
                updatedAt: 1000,
            },
        ]

        render(
            <EnvironmentPicker
                projectId="proj-1"
                projects={mockProjects}
            />,
        )

        await user.click(screen.getByRole('button', { name: /Environment/i }))
        await user.click(screen.getByRole('menuitem', { name: /Set up project/i }))

        expect(openedSettingsSection).toBe('environments')
        expect(openedSettingsParams).toEqual({
            projectId: 'proj-1',
            mode: 'detail',
            fromChat: true,
        })
        expect(screen.queryByRole('menu')).not.toBeInTheDocument()
    })

    it('opens environments section in settings on clicking setup project with selected value', async () => {
        const user = userEvent.setup()
        const mockProjects: Project[] = [
            {
                id: 'proj-1',
                name: 'Backend API Project',
                path: '/workspaces/backend-api',
                pinned: false,
                createdAt: 1000,
                updatedAt: 1000,
            },
            {
                id: 'proj-2',
                name: 'Frontend Client Project',
                path: '/workspaces/frontend-client',
                pinned: false,
                createdAt: 2000,
                updatedAt: 2000,
            },
        ]

        render(
            <EnvironmentPicker
                value="proj-2"
                projects={mockProjects}
            />,
        )

        await user.click(screen.getByRole('button', { name: /Environment/i }))
        await user.click(screen.getByRole('menuitem', { name: /Set up project/i }))

        expect(openedSettingsSection).toBe('environments')
        expect(openedSettingsParams).toEqual({
            projectId: 'proj-2',
            mode: 'detail',
            fromChat: true,
        })
    })

    it('closes on Escape key press', async () => {
        const user = userEvent.setup()
        render(<EnvironmentPicker />)

        await user.click(screen.getByRole('button', { name: /Environment/i }))
        expect(screen.getByRole('menu')).toBeInTheDocument()

        await user.keyboard('{Escape}')
        expect(screen.queryByRole('menu')).not.toBeInTheDocument()
    })

    it('is disabled when disabled prop is true', async () => {
        const user = userEvent.setup()
        render(<EnvironmentPicker disabled />)

        const button = screen.getByRole('button', { name: /Environment/i })
        expect(button).toBeDisabled()

        await user.click(button)
        expect(screen.queryByRole('menu')).not.toBeInTheDocument()
    })

    it('only shows environment for the current project and does not show other projects', async () => {
        const user = userEvent.setup()
        const onChange = vi.fn()

        const mockProjects: Project[] = [
            {
                id: 'proj-1',
                name: 'Backend API Project',
                path: '/workspaces/backend-api',
                pinned: false,
                createdAt: 1000,
                updatedAt: 1000,
            },
            {
                id: 'proj-2',
                name: 'Frontend Client Project',
                path: '/workspaces/frontend-client',
                pinned: false,
                createdAt: 2000,
                updatedAt: 2000,
            },
            {
                id: 'proj-3',
                name: 'Docs Project Without Env',
                path: '/workspaces/docs-project',
                pinned: false,
                createdAt: 3000,
                updatedAt: 3000,
            },
        ]

        const mockReadFileBridge = {
            ReadFile: vi.fn().mockImplementation(async (filePath: string) => {
                // Backend API has .cpa/environments/environment.toml
                if (filePath.startsWith('/workspaces/backend-api/.cpa/environments/environment.toml')) {
                    return { dataBase64: btoa(SAMPLE_TOML) }
                }
                // Frontend Client has root environment.toml
                if (filePath === '/workspaces/frontend-client/environment.toml') {
                    return { dataBase64: btoa(SAMPLE_TOML) }
                }
                throw new Error('File not found')
            }),
        }

        render(
            <EnvironmentPicker
                projectId="proj-1"
                projects={mockProjects}
                readFileBridge={mockReadFileBridge}
                onChange={onChange}
            />,
        )

        // Wait for async detection
        await waitFor(() => {
            expect(mockReadFileBridge.ReadFile).toHaveBeenCalled()
        })

        // Open menu
        await user.click(screen.getByRole('button', { name: /Environment/i }))

        // Current project with environment.toml should be listed
        expect(screen.getByRole('menuitem', { name: /Backend API Project/ })).toBeInTheDocument()

        // Other projects (even with environment.toml) should NOT be listed
        expect(screen.queryByRole('menuitem', { name: /Frontend Client Project/ })).not.toBeInTheDocument()
        expect(screen.queryByRole('menuitem', { name: /Docs Project Without Env/ })).not.toBeInTheDocument()

        // Click Backend API Project
        await user.click(screen.getByRole('menuitem', { name: /Backend API Project/ }))

        expect(onChange).toHaveBeenCalledWith('proj-1')
        expect(screen.queryByRole('menu')).not.toBeInTheDocument()

        // Label should update to selected project name
        expect(screen.getByRole('button', { name: /Environment/i })).toHaveTextContent('Backend API Project')
    })

    it('does not display any project environment when projectId is null or current project has no environment', async () => {
        const user = userEvent.setup()
        const mockProjects: Project[] = [
            {
                id: 'proj-1',
                name: 'Backend API Project',
                path: '/workspaces/backend-api',
                pinned: false,
                createdAt: 1000,
                updatedAt: 1000,
            },
            {
                id: 'proj-3',
                name: 'Docs Project Without Env',
                path: '/workspaces/docs-project',
                pinned: false,
                createdAt: 3000,
                updatedAt: 3000,
            },
        ]

        const mockReadFileBridge = {
            ReadFile: vi.fn().mockImplementation(async (filePath: string) => {
                if (filePath.startsWith('/workspaces/backend-api/.cpa/environments/environment.toml')) {
                    return { dataBase64: btoa(SAMPLE_TOML) }
                }
                throw new Error('File not found')
            }),
        }

        const { rerender } = render(
            <EnvironmentPicker
                projectId="proj-3"
                projects={mockProjects}
                readFileBridge={mockReadFileBridge}
            />,
        )

        await user.click(screen.getByRole('button', { name: /Environment/i }))
        expect(screen.queryByRole('menuitem', { name: /Backend API Project/ })).not.toBeInTheDocument()
        expect(screen.queryByRole('menuitem', { name: /Docs Project/ })).not.toBeInTheDocument()
        expect(screen.getByRole('menuitem', { name: /Work without environment/i })).toBeInTheDocument()

        // Rerender with projectId=null (no project)
        rerender(
            <EnvironmentPicker
                projectId={null}
                projects={mockProjects}
                readFileBridge={mockReadFileBridge}
            />,
        )

        expect(screen.queryByRole('menuitem', { name: /Backend API Project/ })).not.toBeInTheDocument()
        expect(screen.getByRole('menuitem', { name: /Work without environment/i })).toBeInTheDocument()
    })

    it('does not show name of a different project when value belongs to another project', async () => {
        const mockProjects: Project[] = [
            {
                id: 'proj-1',
                name: 'Backend API Project',
                path: '/workspaces/backend-api',
                pinned: false,
                createdAt: 1000,
                updatedAt: 1000,
            },
            {
                id: 'proj-2',
                name: 'Frontend Client Project',
                path: '/workspaces/frontend-client',
                pinned: false,
                createdAt: 2000,
                updatedAt: 2000,
            },
        ]

        render(
            <EnvironmentPicker
                projectId="proj-1"
                value="proj-2"
                projects={mockProjects}
            />,
        )

        // Should display 'No environment' rather than 'Frontend Client Project'
        expect(screen.getByRole('button', { name: /Environment/i })).toHaveTextContent('No environment')
    })

    it('displays selected project name when controlled value is provided', async () => {
        const mockProjects: Project[] = [
            {
                id: 'proj-1',
                name: 'Backend API Project',
                path: '/workspaces/backend-api',
                pinned: false,
                createdAt: 1000,
                updatedAt: 1000,
            },
        ]

        const mockReadFileBridge = {
            ReadFile: vi.fn().mockImplementation(async (filePath: string) => {
                if (filePath.includes('environment.toml')) {
                    return { dataBase64: btoa(SAMPLE_TOML) }
                }
                throw new Error('File not found')
            }),
        }

        render(
            <EnvironmentPicker
                value="proj-1"
                projects={mockProjects}
                readFileBridge={mockReadFileBridge}
            />,
        )

        expect(screen.getByRole('button', { name: /Environment/i })).toHaveTextContent('Backend API Project')
    })

    it('uses leading-normal instead of leading-none on trigger button', () => {
        render(<EnvironmentPicker />)
        const trigger = screen.getByRole('button', { name: /Environment/i })
        expect(trigger.className).toContain('leading-normal')
        expect(trigger.className).not.toContain('leading-none')
    })
})
