/**
 * Default Keyboard Shortcuts Definitions
 * Autonomous Settings Plugin
 */

import type { ShortcutItem, ShortcutKeyBinding } from '@cpa/plugin-api'

const sc = (meta: boolean, ctrl: boolean, alt: boolean, shift: boolean, key: string): ShortcutKeyBinding => ({
    ctrl,
    alt,
    shift,
    meta,
    key,
})

export const DEFAULT_SHORTCUT_ITEMS: ShortcutItem[] = [
    {
        id: 'new-chat',
        titleKey: 'shortcuts.item.newChat.title',
        titleZh: 'New chat',
        titleEn: 'New chat',
        descKey: 'shortcuts.item.newChat.desc',
        descZh: 'Start a new chat',
        descEn: 'Start a new chat',
        defaultShortcuts: [
            sc(true, false, false, false, 'N'),
            sc(true, false, false, true, 'O'),
        ],
    },
    {
        id: 'new-standalone-chat',
        titleKey: 'shortcuts.item.newStandaloneChat.title',
        titleZh: 'New standalone chat',
        titleEn: 'New standalone chat',
        descKey: 'shortcuts.item.newStandaloneChat.desc',
        descZh: 'Start a new chat outside of project',
        descEn: 'Start a new chat outside of project',
        defaultShortcuts: [
            sc(true, false, true, false, 'O'),
        ],
    },
    {
        id: 'next-chat',
        titleKey: 'shortcuts.item.nextChat.title',
        titleZh: 'Next chat',
        titleEn: 'Next chat',
        descKey: 'shortcuts.item.nextChat.desc',
        descZh: 'Switch to next chat',
        descEn: 'Switch to next chat',
        defaultShortcuts: [
            sc(true, false, false, true, ']'),
            sc(true, false, true, false, 'ArrowRight'),
        ],
    },
    {
        id: 'previous-chat',
        titleKey: 'shortcuts.item.previousChat.title',
        titleZh: 'Previous chat',
        titleEn: 'Previous chat',
        descKey: 'shortcuts.item.previousChat.desc',
        descZh: 'Switch to previous chat',
        descEn: 'Switch to previous chat',
        defaultShortcuts: [
            sc(true, false, false, true, '['),
            sc(true, false, true, false, 'ArrowLeft'),
        ],
    },
    {
        id: 'archive-chat',
        titleKey: 'shortcuts.item.archiveChat.title',
        titleZh: 'Archive chat',
        titleEn: 'Archive chat',
        descKey: 'shortcuts.item.archiveChat.desc',
        descZh: 'Archive current chat',
        descEn: 'Archive current chat',
        defaultShortcuts: [
            sc(true, false, false, true, 'A'),
        ],
    },
    {
        id: 'toggle-pin',
        titleKey: 'shortcuts.item.togglePin.title',
        titleZh: 'Toggle pin',
        titleEn: 'Toggle pin',
        descKey: 'shortcuts.item.togglePin.desc',
        descZh: 'Pin or unpin current chat',
        descEn: 'Pin or unpin current chat',
        defaultShortcuts: [
            sc(true, false, true, false, 'P'),
        ],
    },
    {
        id: 'mark-as-unread',
        titleKey: 'shortcuts.item.markAsUnread.title',
        titleZh: 'Mark as unread',
        titleEn: 'Mark as unread',
        descKey: 'shortcuts.item.markAsUnread.desc',
        descZh: 'Mark current chat as unread',
        descEn: 'Mark current chat as unread',
        defaultShortcuts: [
            sc(true, false, false, true, 'U'),
        ],
    },
    {
        id: 'fork-chat',
        titleKey: 'shortcuts.item.forkChat.title',
        titleZh: 'Fork chat',
        titleEn: 'Fork chat',
        descKey: 'shortcuts.item.forkChat.desc',
        descZh: 'Create a fork of current chat',
        descEn: 'Create a fork of current chat',
        defaultShortcuts: [],
    },
    {
        id: 'switch-chat',
        titleKey: 'shortcuts.item.switchChat.title',
        titleZh: 'Switch chat…',
        titleEn: 'Switch chat…',
        descKey: 'shortcuts.item.switchChat.desc',
        descZh: 'Search and switch to chat',
        descEn: 'Search and switch to chat',
        defaultShortcuts: [
            sc(true, false, false, false, 'K'),
        ],
    },
    {
        id: 'focus-main-chat-input',
        titleKey: 'shortcuts.item.focusMainChatInput.title',
        titleZh: 'Focus main chat input',
        titleEn: 'Focus main chat input',
        descKey: 'shortcuts.item.focusMainChatInput.desc',
        descZh: 'Move keyboard focus to main chat input',
        descEn: 'Move keyboard focus to main chat input',
        defaultShortcuts: [
            sc(true, false, false, false, 'I'),
        ],
    },
    {
        id: 'toggle-sidebar',
        titleKey: 'shortcuts.item.toggleSidebar.title',
        titleZh: 'Toggle sidebar',
        titleEn: 'Toggle sidebar',
        descKey: 'shortcuts.item.toggleSidebar.desc',
        descZh: 'Show or hide sidebar',
        descEn: 'Show or hide sidebar',
        defaultShortcuts: [
            sc(true, false, false, false, 'B'),
        ],
    },
    {
        id: 'toggle-bottom-panel',
        titleKey: 'shortcuts.item.toggleBottomPanel.title',
        titleZh: 'Toggle bottom panel',
        titleEn: 'Toggle bottom panel',
        descKey: 'shortcuts.item.toggleBottomPanel.desc',
        descZh: 'Show or hide bottom panel',
        descEn: 'Show or hide bottom panel',
        defaultShortcuts: [
            sc(true, false, false, false, 'J'),
        ],
    },
    {
        id: 'settings',
        titleKey: 'shortcuts.item.settings.title',
        titleZh: 'Settings',
        titleEn: 'Settings',
        descKey: 'shortcuts.item.settings.desc',
        descZh: 'Open CPA settings',
        descEn: 'Open CPA settings',
        defaultShortcuts: [
            sc(true, false, false, false, ','),
        ],
    },
    {
        id: 'cycle-reasoning-effort',
        titleKey: 'shortcuts.item.cycleReasoningEffort.title',
        titleZh: 'Cycle reasoning effort',
        titleEn: 'Cycle reasoning effort',
        descKey: 'shortcuts.item.cycleReasoningEffort.desc',
        descZh: 'Cycle reasoning effort options in editor',
        descEn: 'Cycle reasoning effort options in editor',
        defaultShortcuts: [
            sc(false, false, false, true, 'Tab'),
        ],
    },
    {
        id: 'next-model',
        titleKey: 'shortcuts.item.nextModel.title',
        titleZh: 'Next model',
        titleEn: 'Next model',
        descKey: 'shortcuts.item.nextModel.desc',
        descZh: 'Switch to next model in editor',
        descEn: 'Switch to next model in editor',
        defaultShortcuts: [
            sc(false, true, false, false, 'P'),
        ],
    },
    {
        id: 'previous-model',
        titleKey: 'shortcuts.item.previousModel.title',
        titleZh: 'Previous model',
        titleEn: 'Previous model',
        descKey: 'shortcuts.item.previousModel.desc',
        descZh: 'Switch to previous model in editor',
        descEn: 'Switch to previous model in editor',
        defaultShortcuts: [
            sc(false, true, false, true, 'P'),
        ],
    },
    {
        id: 'open-model-selector',
        titleKey: 'shortcuts.item.openModelSelector.title',
        titleZh: 'Open model selector',
        titleEn: 'Open model selector',
        descKey: 'shortcuts.item.openModelSelector.desc',
        descZh: 'Open editor model selector',
        descEn: 'Open editor model selector',
        defaultShortcuts: [
            sc(false, true, false, true, 'M'),
        ],
    },
    {
        id: 'open-folder',
        titleKey: 'shortcuts.item.openFolder.title',
        titleZh: 'Open folder',
        titleEn: 'Open folder',
        descKey: 'shortcuts.item.openFolder.desc',
        descZh: 'Add local project to CPA',
        descEn: 'Add local project to CPA',
        defaultShortcuts: [
            sc(true, false, false, false, 'O'),
        ],
    },
    {
        id: 'open-terminal',
        titleKey: 'shortcuts.item.openTerminal.title',
        titleZh: 'Open terminal',
        titleEn: 'Open terminal',
        descKey: 'shortcuts.item.openTerminal.desc',
        descZh: 'Open terminal panel',
        descEn: 'Open terminal panel',
        defaultShortcuts: [
            sc(false, true, false, false, '`'),
        ],
    },
    {
        id: 'open-review-tab',
        titleKey: 'shortcuts.item.openReviewTab.title',
        titleZh: 'Open review tab',
        titleEn: 'Open review tab',
        descKey: 'shortcuts.item.openReviewTab.desc',
        descZh: 'Open review tab',
        descEn: 'Open review tab',
        defaultShortcuts: [
            sc(false, true, false, true, 'G'),
        ],
    },
    {
        id: 'toggle-review-panel',
        titleKey: 'shortcuts.item.toggleReviewPanel.title',
        titleZh: 'Toggle review panel',
        titleEn: 'Toggle review panel',
        descKey: 'shortcuts.item.toggleReviewPanel.desc',
        descZh: 'Show or hide review for current chat',
        descEn: 'Show or hide review for current chat',
        defaultShortcuts: [
            sc(true, false, true, false, 'B'),
        ],
    },
    {
        id: 'toggle-activity-view',
        titleKey: 'shortcuts.item.toggleActivityView.title',
        titleZh: 'Toggle activity view',
        titleEn: 'Toggle activity view',
        descKey: 'shortcuts.item.toggleActivityView.desc',
        descZh: 'Toggle sidebar activity view',
        descEn: 'Toggle sidebar activity view',
        defaultShortcuts: [
            sc(true, false, true, false, 'U'),
        ],
    },
    {
        id: 'search-files',
        titleKey: 'shortcuts.item.searchFiles.title',
        titleZh: 'Search files…',
        titleEn: 'Search files…',
        descKey: 'shortcuts.item.searchFiles.desc',
        descZh: 'Search files',
        descEn: 'Search files',
        defaultShortcuts: [
            sc(true, false, false, false, 'P'),
        ],
    },
    {
        id: 'open-browser-tab',
        titleKey: 'shortcuts.item.openBrowserTab.title',
        titleZh: 'Open browser tab',
        titleEn: 'Open browser tab',
        descKey: 'shortcuts.item.openBrowserTab.desc',
        descZh: 'Open new browser tab',
        descEn: 'Open new browser tab',
        defaultShortcuts: [
            sc(true, false, false, false, 'T'),
        ],
    },
    {
        id: 'toggle-browser-panel',
        titleKey: 'shortcuts.item.toggleBrowserPanel.title',
        titleZh: 'Show/hide browser panel',
        titleEn: 'Show/hide browser panel',
        descKey: 'shortcuts.item.toggleBrowserPanel.desc',
        descZh: 'Show or hide browser panel',
        descEn: 'Show or hide browser panel',
        defaultShortcuts: [
            sc(true, false, false, true, 'B'),
        ],
    },
    {
        id: 'reload-browser-page',
        titleKey: 'shortcuts.item.reloadBrowserPage.title',
        titleZh: 'Reload browser page',
        titleEn: 'Reload browser page',
        descKey: 'shortcuts.item.reloadBrowserPage.desc',
        descZh: 'Reload current browser page',
        descEn: 'Reload current browser page',
        defaultShortcuts: [
            sc(true, false, false, false, 'R'),
        ],
    },
    {
        id: 'force-reload-browser-page',
        titleKey: 'shortcuts.item.forceReloadBrowserPage.title',
        titleZh: 'Force reload browser page',
        titleEn: 'Force reload browser page',
        descKey: 'shortcuts.item.forceReloadBrowserPage.desc',
        descZh: 'Force reload current browser page',
        descEn: 'Force reload current browser page',
        defaultShortcuts: [
            sc(true, false, false, true, 'R'),
        ],
    },
    {
        id: 'browser-back',
        titleKey: 'shortcuts.item.browserBack.title',
        titleZh: 'Browser back',
        titleEn: 'Browser back',
        descKey: 'shortcuts.item.browserBack.desc',
        descZh: 'Go back to previous page in browser history',
        descEn: 'Go back to previous page in browser history',
        defaultShortcuts: [
            sc(true, false, false, false, 'ArrowLeft'),
        ],
    },
    {
        id: 'browser-forward',
        titleKey: 'shortcuts.item.browserForward.title',
        titleZh: 'Browser forward',
        titleEn: 'Browser forward',
        descKey: 'shortcuts.item.browserForward.desc',
        descZh: 'Go forward in browser history',
        descEn: 'Go forward in browser history',
        defaultShortcuts: [
            sc(true, false, false, false, 'ArrowRight'),
        ],
    },
    {
        id: 'focus-browser-address-bar',
        titleKey: 'shortcuts.item.focusBrowserAddressBar.title',
        titleZh: 'Focus browser address bar',
        titleEn: 'Focus browser address bar',
        descKey: 'shortcuts.item.focusBrowserAddressBar.desc',
        descZh: 'Focus in-app browser address bar',
        descEn: 'Focus in-app browser address bar',
        defaultShortcuts: [
            sc(true, false, false, false, 'L'),
        ],
    },
    {
        id: 'navigate-back',
        titleKey: 'shortcuts.item.navigateBack.title',
        titleZh: 'Back',
        titleEn: 'Back',
        descKey: 'shortcuts.item.navigateBack.desc',
        descZh: 'Go back in navigation history',
        descEn: 'Go back in navigation history',
        defaultShortcuts: [
            sc(true, false, false, false, '['),
        ],
    },
    {
        id: 'navigate-forward',
        titleKey: 'shortcuts.item.navigateForward.title',
        titleZh: 'Forward',
        titleEn: 'Forward',
        descKey: 'shortcuts.item.navigateForward.desc',
        descZh: 'Go forward in navigation history',
        descEn: 'Go forward in navigation history',
        defaultShortcuts: [
            sc(true, false, false, false, ']'),
        ],
    },
    {
        id: 'stop-execution',
        titleKey: 'shortcuts.item.stopExecution.title',
        titleZh: '暂停当前执行',
        titleEn: 'Stop execution',
        descKey: 'shortcuts.item.stopExecution.desc',
        descZh: '暂停当前正在执行的任务',
        descEn: 'Stop or pause current execution',
        defaultShortcuts: [
            sc(false, false, false, false, 'Escape'),
        ],
    },
]

export const IMPLEMENTED_SHORTCUT_IDS = new Set<string>(
    DEFAULT_SHORTCUT_ITEMS.map((item) => item.id),
)
