import { fireEvent, render, screen } from '@testing-library/react'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import i18n from '@/i18n'
import { useProjectStore } from '@/stores/projectStore'
import { useUiStore } from '@/stores/uiStore'
import { getHostServices } from '@/application/services/createHostServices'
import { EnvironmentsSection } from './EnvironmentsSection.js'

const MOCK_PROJECTS = [
    {
        id: 'proj-1',
        name: 'EasyCLIProxyAPI',
        path: '/workspaces/EasyCLIProxyAPI',
        paths: ['/workspaces/EasyCLIProxyAPI'],
        pinned: true,
        createdAt: 1000,
        updatedAt: 3000,
    },
    {
        id: 'proj-2',
        name: 'pi-cliproxyapi-provider',
        path: '/workspaces/pi-cliproxyapi-provider',
        paths: ['/workspaces/pi-cliproxyapi-provider'],
        pinned: false,
        createdAt: 2000,
        updatedAt: 2000,
    },
    {
        id: 'proj-3',
        name: 'no-path-project',
        pinned: false,
        createdAt: 500,
        updatedAt: 500,
    },
]

beforeEach(async () => {
    getHostServices()
    await i18n.changeLanguage('en')
    useProjectStore.setState({ projects: MOCK_PROJECTS })
})

describe('EnvironmentsSection', () => {
    it('renders the environments page header and description', () => {
        render(<EnvironmentsSection />)

        expect(
            screen.getByRole('heading', { level: 1, name: 'Environments' })
        ).toBeInTheDocument()
        expect(
            screen.getByText(
                'Local environments tell CPA how to set up worktrees for a project.',
            ),
        ).toBeInTheDocument()
        expect(
            screen.getByText('Learn more.')
        ).toBeInTheDocument()
    })

    it('renders the select project header and add project button', () => {
        render(<EnvironmentsSection />)

        expect(
            screen.getByRole('heading', { level: 2, name: 'Select project' })
        ).toBeInTheDocument()
        expect(
            screen.getByRole('button', { name: 'Add project' })
        ).toBeInTheDocument()
    })

    it('renders the list of projects from project store', () => {
        render(<EnvironmentsSection />)

        expect(screen.getByText('EasyCLIProxyAPI')).toBeInTheDocument()
        expect(screen.getByText('/workspaces/EasyCLIProxyAPI')).toBeInTheDocument()
        expect(screen.getByText('pi-cliproxyapi-provider')).toBeInTheDocument()
        expect(screen.getByText('/workspaces/pi-cliproxyapi-provider')).toBeInTheDocument()
        expect(screen.getByText('no-path-project')).toBeInTheDocument()
        expect(screen.getByText('No path set')).toBeInTheDocument()
    })

    it('renders empty state when there are no projects in store', () => {
        useProjectStore.setState({ projects: [] })
        render(<EnvironmentsSection />)

        expect(screen.getByText('No projects yet')).toBeInTheDocument()
    })

    it('renders empty state in detail view when no environment.toml is found', () => {
        render(<EnvironmentsSection />)

        fireEvent.click(screen.getByText('EasyCLIProxyAPI'))

        expect(
            screen.getByRole('heading', { level: 1, name: 'Environments' })
        ).toBeInTheDocument()
        expect(
            screen.getByRole('button', { name: 'Create local environment' })
        ).toBeInTheDocument()
        expect(
            screen.getByText('This project does not have a local environment configured')
        ).toBeInTheDocument()

        // Breadcrumb in detail view
        const breadcrumbNav = screen.getByRole('navigation', { name: 'Breadcrumb' })
        expect(breadcrumbNav).toHaveTextContent('Environments')
        expect(breadcrumbNav).toHaveTextContent('EasyCLIProxyAPI')
    })

    it('opens edit view on clicking Create local environment from empty detail view', () => {
        render(<EnvironmentsSection />)

        fireEvent.click(screen.getByText('EasyCLIProxyAPI'))
        fireEvent.click(screen.getByRole('button', { name: 'Create local environment' }))

        expect(
            screen.getByRole('heading', { level: 1, name: 'Edit local environment' })
        ).toBeInTheDocument()
        expect(screen.getByRole('button', { name: 'Save' })).toBeInTheDocument()
    })

    it('opens configured detail view when environment.toml is present', async () => {
        const sampleToml = `# THIS IS AUTOGENERATED. DO NOT EDIT MANUALLY
version = 1
name = "EasyCLIProxyAPI"

[setup]
script = "cd \\"$CODEX_SOURCE_TREE_PATH\\""

[cleanup]
script = "cd \\"$CODEX_WORKTREE_PATH\\""
`
        const mockReadFile = vi.fn().mockResolvedValue({ dataBase64: btoa(sampleToml) })

        render(<EnvironmentsSection readFileBridge={{ ReadFile: mockReadFile }} />)

        fireEvent.click(screen.getByText('EasyCLIProxyAPI'))

        // Detail view header
        await screen.findByRole('heading', { level: 1, name: 'EasyCLIProxyAPI' })
        expect(screen.getByRole('button', { name: 'Edit' })).toBeInTheDocument()

        // Breadcrumb in detail view
        const breadcrumbNav = screen.getByRole('navigation', { name: 'Breadcrumb' })
        expect(breadcrumbNav).toHaveTextContent('Environments')
        expect(breadcrumbNav).toHaveTextContent('EasyCLIProxyAPI')

        // Setup script section
        expect(screen.getByText('Setup script')).toBeInTheDocument()
        expect(screen.getByText('This script will run when creating a worktree')).toBeInTheDocument()
        expect(screen.getByText('Variables')).toBeInTheDocument()
        expect(screen.getByText('"$CODEX_SOURCE_TREE_PATH"')).toBeInTheDocument()

        // Cleanup script section
        expect(screen.getByText('Cleanup script')).toBeInTheDocument()
        expect(screen.getByText('Runs in the project root before cleaning up a worktree')).toBeInTheDocument()
        expect(screen.getByText('"$CODEX_WORKTREE_PATH"')).toBeInTheDocument()

        // Actions section
        expect(screen.getByText('Actions')).toBeInTheDocument()
        expect(screen.getByText('These actions can run any command and appear in the top bar')).toBeInTheDocument()
        expect(
            screen.getByText('Add actions to run commands from the local toolbar')
        ).toBeInTheDocument()
    })

    it('opens edit view directly when clicking the Add (Plus) button on a project without environment', () => {
        render(<EnvironmentsSection />)

        const addBtn = screen.getByRole('button', {
            name: 'Add environment for pi-cliproxyapi-provider',
        })
        fireEvent.click(addBtn)

        expect(
            screen.getByRole('heading', { level: 1, name: 'Edit local environment' })
        ).toBeInTheDocument()
        expect(screen.getByLabelText('Name', { selector: '#env-project-name' })).toHaveValue(
            'pi-cliproxyapi-provider'
        )
    })

    it('returns to list view when clicking Environments breadcrumb in detail view', () => {
        render(<EnvironmentsSection />)

        fireEvent.click(screen.getByText('EasyCLIProxyAPI'))
        expect(
            screen.getByText('This project does not have a local environment configured')
        ).toBeInTheDocument()

        const breadcrumbNav = screen.getByRole('navigation', { name: 'Breadcrumb' })
        fireEvent.click(breadcrumbNav.querySelector('button')!)

        expect(
            screen.getByRole('heading', { level: 1, name: 'Environments' })
        ).toBeInTheDocument()
        expect(screen.getByText('Select project')).toBeInTheDocument()
    })

    it('opens edit view on clicking Create local environment or Edit button', () => {
        render(<EnvironmentsSection />)

        fireEvent.click(screen.getByText('EasyCLIProxyAPI'))

        fireEvent.click(screen.getByRole('button', { name: 'Create local environment' }))

        expect(
            screen.getByRole('heading', { level: 1, name: 'Edit local environment' })
        ).toBeInTheDocument()
        expect(screen.getByRole('button', { name: 'Save' })).toBeInTheDocument()

        // Breadcrumb in edit view has 3 segments: Environments > EasyCLIProxyAPI > Edit
        const breadcrumbNav = screen.getByRole('navigation', { name: 'Breadcrumb' })
        expect(breadcrumbNav).toHaveTextContent('Environments')
        expect(breadcrumbNav).toHaveTextContent('EasyCLIProxyAPI')
        expect(breadcrumbNav).toHaveTextContent('Edit')
    })

    it('returns to detail view when clicking middle project breadcrumb from edit view', async () => {
        const sampleToml = `version = 1\nname = "EasyCLIProxyAPI"\n[setup]\nscript = "npm test"`
        const mockReadFile = vi.fn().mockResolvedValue({ dataBase64: btoa(sampleToml) })

        render(<EnvironmentsSection readFileBridge={{ ReadFile: mockReadFile }} />)

        fireEvent.click(screen.getByText('EasyCLIProxyAPI'))
        await screen.findByRole('heading', { level: 1, name: 'EasyCLIProxyAPI' })
        fireEvent.click(screen.getByRole('button', { name: 'Edit' }))

        expect(
            screen.getByRole('heading', { level: 1, name: 'Edit local environment' })
        ).toBeInTheDocument()

        const breadcrumbNav = screen.getByRole('navigation', { name: 'Breadcrumb' })
        const projectBtn = screen.getByRole('button', { name: 'EasyCLIProxyAPI' })
        expect(breadcrumbNav).toContainElement(projectBtn)

        fireEvent.click(projectBtn)

        // Returns to detail view
        expect(
            screen.getByRole('heading', { level: 1, name: 'EasyCLIProxyAPI' })
        ).toBeInTheDocument()
        expect(screen.getByText('This script will run when creating a worktree')).toBeInTheDocument()
    })

    it('returns to list view when clicking Environments breadcrumb from edit view', () => {
        render(<EnvironmentsSection />)

        fireEvent.click(screen.getByText('EasyCLIProxyAPI'))
        fireEvent.click(screen.getByRole('button', { name: 'Create local environment' }))

        const envBtn = screen.getByRole('button', { name: 'Environments' })
        fireEvent.click(envBtn)

        expect(
            screen.getByRole('heading', { level: 1, name: 'Environments' })
        ).toBeInTheDocument()
        expect(screen.getByText('Select project')).toBeInTheDocument()
    })

    it('updates project name and scripts when saving in edit view', async () => {
        const mockWriteFile = vi.fn().mockResolvedValue(undefined)
        render(
            <EnvironmentsSection
                writeFileBridge={{
                    ReadFile: vi.fn().mockRejectedValue(new Error('ENOENT')),
                    WriteFile: mockWriteFile,
                }}
            />
        )

        fireEvent.click(screen.getByText('EasyCLIProxyAPI'))
        fireEvent.click(screen.getByRole('button', { name: 'Create local environment' }))

        const nameInput = screen.getByLabelText('Name', { selector: '#env-project-name' })
        fireEvent.change(nameInput, { target: { value: 'EasyCLIProxyAPI-Renamed' } })

        const setupTextarea = screen.getByLabelText('Setup script')
        fireEvent.change(setupTextarea, { target: { value: 'npm run build' } })

        fireEvent.click(screen.getByRole('button', { name: 'Save' }))

        // After save, returns to detail view of renamed project
        expect(
            screen.getByRole('heading', { level: 1, name: 'EasyCLIProxyAPI-Renamed' })
        ).toBeInTheDocument()
        expect(
            screen.getAllByText((_, el) => el?.textContent === 'npm run build').length
        ).toBeGreaterThan(0)
    })

    it('adds a new project via directory picker when clicking add project', async () => {
        const mockPicker = vi.fn().mockResolvedValue({
            name: 'NewProject',
            path: '/workspaces/NewProject',
        })

        render(<EnvironmentsSection directoryPicker={mockPicker} />)

        fireEvent.click(screen.getByRole('button', { name: 'Add project' }))

        expect(mockPicker).toHaveBeenCalled()
    })

    it('toggles the variables popover and copies variable in detail view', async () => {
        const sampleToml = `version = 1\nname = "EasyCLIProxyAPI"`
        const mockReadFile = vi.fn().mockResolvedValue({ dataBase64: btoa(sampleToml) })
        const writeTextMock = vi.fn().mockResolvedValue(undefined)
        Object.assign(navigator, {
            clipboard: {
                writeText: writeTextMock,
            },
        })

        render(<EnvironmentsSection readFileBridge={{ ReadFile: mockReadFile }} />)

        fireEvent.click(screen.getByText('EasyCLIProxyAPI'))
        await screen.findByRole('heading', { level: 1, name: 'EasyCLIProxyAPI' })

        const varBtn = screen.getByRole('button', { name: 'Variables' })
        expect(screen.queryByTestId('env-variables-popover')).not.toBeInTheDocument()

        // Open popover
        fireEvent.click(varBtn)
        expect(screen.getByTestId('env-variables-popover')).toBeInTheDocument()
        expect(screen.getByText('Setup script environment variables')).toBeInTheDocument()
        expect(screen.getByText('Source workspace path')).toBeInTheDocument()
        expect(screen.getByText('CODEX_SOURCE_TREE_PATH')).toBeInTheDocument()
        expect(screen.getByText('New worktree path')).toBeInTheDocument()
        expect(screen.getByText('CODEX_WORKTREE_PATH')).toBeInTheDocument()

        // Click variable to copy
        const sourceTreeBtn = screen.getByText('CODEX_SOURCE_TREE_PATH').closest('button')!
        fireEvent.click(sourceTreeBtn)
        expect(writeTextMock).toHaveBeenCalledWith('CODEX_SOURCE_TREE_PATH')

        const worktreeBtn = screen.getByText('CODEX_WORKTREE_PATH').closest('button')!
        fireEvent.click(worktreeBtn)
        expect(writeTextMock).toHaveBeenCalledWith('CODEX_WORKTREE_PATH')

        // Close on Escape
        fireEvent.keyDown(document, { key: 'Escape' })
        expect(screen.queryByTestId('env-variables-popover')).not.toBeInTheDocument()
    })

    it('copies script from code viewer in detail view', async () => {
        const sampleToml = `version = 1\nname = "EasyCLIProxyAPI"`
        const mockReadFile = vi.fn().mockResolvedValue({ dataBase64: btoa(sampleToml) })
        const writeTextMock = vi.fn().mockResolvedValue(undefined)
        Object.assign(navigator, {
            clipboard: {
                writeText: writeTextMock,
            },
        })

        render(<EnvironmentsSection readFileBridge={{ ReadFile: mockReadFile }} />)

        fireEvent.click(screen.getByText('EasyCLIProxyAPI'))
        await screen.findByRole('heading', { level: 1, name: 'EasyCLIProxyAPI' })

        const copyBtns = screen.getAllByRole('button', { name: 'Click to copy' })
        expect(copyBtns.length).toBeGreaterThanOrEqual(2)

        fireEvent.click(copyBtns[0]!)
        expect(writeTextMock).toHaveBeenCalledWith('cd "$CODEX_SOURCE_TREE_PATH"')

        fireEvent.click(copyBtns[1]!)
        expect(writeTextMock).toHaveBeenCalledWith('cd "$CODEX_WORKTREE_PATH"')
    })

    it('renders input boxes with placeholders in edit view', () => {
        render(<EnvironmentsSection />)

        fireEvent.click(screen.getByText('EasyCLIProxyAPI'))
        fireEvent.click(screen.getByRole('button', { name: 'Create local environment' }))

        const setupTextarea = screen.getByLabelText('Setup script') as HTMLTextAreaElement
        expect(setupTextarea.value).toBe('')
        expect(setupTextarea.placeholder).toContain('cd "$CODEX_WORKTREE_PATH"')

        const cleanupTextarea = screen.getByLabelText('Cleanup script') as HTMLTextAreaElement
        expect(cleanupTextarea.value).toBe('')
        expect(cleanupTextarea.placeholder).toContain('docker compose down --remove-orphans')

        // Click Add action to add an expanded action card
        fireEvent.click(screen.getByRole('button', { name: 'Add action' }))

        const actionNameInputs = screen.getAllByLabelText('Name') as HTMLInputElement[]
        const actionNameInput = actionNameInputs[actionNameInputs.length - 1]!
        expect(actionNameInput.value).toBe('')
        expect(actionNameInput.placeholder).toBe('Action name')

        const actionTextareas = screen.getAllByLabelText('Action script') as HTMLTextAreaElement[]
        const actionTextarea = actionTextareas[actionTextareas.length - 1]!
        expect(actionTextarea.value).toBe('')
        expect(actionTextarea.placeholder).toBe('npm run dev')
    })

    it('expands all existing actions as editable cards in edit view', async () => {
        const tomlWithActions = `version = 1\nname = "EasyCLIProxyAPI"\n[[actions]]\nname = "Run"\nicon = "test"\ncommand = "npm run dev"`
        const mockReadFile = vi.fn().mockResolvedValue({
            dataBase64: btoa(unescape(encodeURIComponent(tomlWithActions))),
        })

        render(<EnvironmentsSection readFileBridge={{ ReadFile: mockReadFile }} />)

        fireEvent.click(screen.getByText('EasyCLIProxyAPI'))
        await screen.findByRole('heading', { level: 1, name: 'EasyCLIProxyAPI' })
        fireEvent.click(screen.getByRole('button', { name: 'Edit' }))

        // Directly verify action inputs are expanded in edit view
        const actionNameInputs = screen.getAllByLabelText('Name') as HTMLInputElement[]
        expect(actionNameInputs.some((input) => input.value === 'Run')).toBe(true)

        const actionTextareas = screen.getAllByLabelText('Action script') as HTMLTextAreaElement[]
        expect(actionTextareas.some((ta) => ta.value === 'npm run dev')).toBe(true)
    })

    it('loads and populates multi-platform scripts from environment.toml into detail view and edit view', async () => {
        const sampleToml = `# THIS IS AUTOGENERATED. DO NOT EDIT MANUALLY
version = 1
name = "EasyCLIProxyAPI"

[setup]
script = "cd \\"$CODEX_SOURCE_TREE_PATH\\""

[setup.darwin]
script = "cd \\"$CODEX_SOURCE_TREE_PATH-macos\\""

[setup.linux]
script = "cd \\"$CODEX_SOURCE_TREE_PATH-linux\\""

[setup.win32]
script = "cd \\"$CODEX_SOURCE_TREE_PATH-windows\\""

[cleanup]
script = "cd \\"$CODEX_WORKTREE_PATH\\""

[cleanup.darwin]
script = "cd \\"$CODEX_WORKTREE_PATH-macos\\""

[cleanup.linux]
script = "cd \\"$CODEX_WORKTREE_PATH-linux\\""

[cleanup.win32]
script = "cd \\"$CODEX_WORKTREE_PATH-windows\\""
`
        const mockReadFile = vi.fn().mockImplementation(async (filePath: string) => {
            if (filePath.includes('.codex/environments/environment.toml')) {
                return { dataBase64: btoa(sampleToml) }
            }
            throw new Error('Not found')
        })

        const mockWriteFile = vi.fn().mockResolvedValue(undefined)
        const mockMkdirAll = vi.fn().mockResolvedValue(undefined)

        render(
            <EnvironmentsSection
                readFileBridge={{ ReadFile: mockReadFile }}
                writeFileBridge={{
                    ReadFile: mockReadFile,
                    WriteFile: mockWriteFile,
                    MkdirAll: mockMkdirAll,
                }}
            />
        )

        // Select EasyCLIProxyAPI project
        fireEvent.click(screen.getByText('EasyCLIProxyAPI'))

        // Wait for detail view and toml load
        await screen.findByRole('heading', { level: 1, name: 'EasyCLIProxyAPI' })
        expect(screen.getByText('"$CODEX_SOURCE_TREE_PATH"')).toBeInTheDocument()
        expect(screen.getByText('"$CODEX_WORKTREE_PATH"')).toBeInTheDocument()

        // Platform tabs in Detail view
        const macosBtns = screen.getAllByRole('button', { name: 'macOS' })
        expect(macosBtns.length).toBeGreaterThanOrEqual(2)

        // Click macOS tab for setup script
        fireEvent.click(macosBtns[0]!)
        expect(screen.getByText('"$CODEX_SOURCE_TREE_PATH-macos"')).toBeInTheDocument()

        // Click macOS tab for cleanup script
        fireEvent.click(macosBtns[1]!)
        expect(screen.getByText('"$CODEX_WORKTREE_PATH-macos"')).toBeInTheDocument()

        // Click Linux tabs
        const linuxBtns = screen.getAllByRole('button', { name: 'Linux' })
        fireEvent.click(linuxBtns[0]!)
        expect(screen.getByText('"$CODEX_SOURCE_TREE_PATH-linux"')).toBeInTheDocument()

        // Click Windows tabs
        const windowsBtns = screen.getAllByRole('button', { name: 'Windows' })
        fireEvent.click(windowsBtns[0]!)
        expect(screen.getByText('"$CODEX_SOURCE_TREE_PATH-windows"')).toBeInTheDocument()

        // Now open Edit View
        fireEvent.click(screen.getByRole('button', { name: 'Edit' }))

        expect(
            screen.getByRole('heading', { level: 1, name: 'Edit local environment' })
        ).toBeInTheDocument()

        const nameInput = screen.getByLabelText('Name', { selector: '#env-project-name' }) as HTMLInputElement
        expect(nameInput.value).toBe('EasyCLIProxyAPI')

        const setupTextarea = screen.getByLabelText('Setup script') as HTMLTextAreaElement
        expect(setupTextarea.value).toBe('cd "$CODEX_SOURCE_TREE_PATH"')

        // Switch platform tab in Edit View to macOS
        const editMacosBtns = screen.getAllByRole('button', { name: 'macOS' })
        fireEvent.click(editMacosBtns[0]!)
        expect(setupTextarea.value).toBe('cd "$CODEX_SOURCE_TREE_PATH-macos"')

        // Edit macOS setup script
        fireEvent.change(setupTextarea, {
            target: { value: 'cd "$CODEX_SOURCE_TREE_PATH-macos" && npm test' },
        })

        // Save
        fireEvent.click(screen.getByRole('button', { name: 'Save' }))

        // After save, returns to detail view and saves to environment.toml
        await screen.findByRole('heading', { level: 1, name: 'EasyCLIProxyAPI' })
        expect(mockWriteFile).toHaveBeenCalled()
    })

    it('shows a right arrow button for projects with environment.toml and plus button for others', async () => {
        const sampleToml = `version = 1\nname = "EasyCLIProxyAPI"`
        const mockReadFile = vi.fn().mockImplementation(async (filePath: string) => {
            if (filePath.includes('/workspaces/EasyCLIProxyAPI/')) {
                return { dataBase64: btoa(sampleToml) }
            }
            throw new Error('Not found')
        })

        render(<EnvironmentsSection readFileBridge={{ ReadFile: mockReadFile }} />)

        // Wait for asynchronous environment check to resolve
        const viewBtn = await screen.findByRole('button', {
            name: 'View environment for EasyCLIProxyAPI',
        })
        expect(viewBtn).toBeInTheDocument()

        // Project without environment.toml keeps the Add (Plus) button
        const addBtn = screen.getByRole('button', {
            name: 'Add environment for pi-cliproxyapi-provider',
        })
        expect(addBtn).toBeInTheDocument()
    })

    it('renders actions with 4 icon types (run, tool, debug, test) loaded from environment.toml', async () => {
        const tomlWithActions = `# THIS IS AUTOGENERATED. DO NOT EDIT MANUALLY
version = 1
name = "EasyCLIProxyAPI"

[setup]
script = "echo setup"

[[actions]]
name = "Run"
icon = "test"
command = "npm run dev"

[[actions]]
name = "Build Tool"
icon = "tool"
command = "npm run build"

[[actions]]
name = "Debug App"
icon = "debug"
command = "npm run debug"

[[actions]]
name = "Start Server"
icon = "run"
command = "npm start"
`
        const mockReadFile = vi.fn().mockResolvedValue({
            dataBase64: btoa(unescape(encodeURIComponent(tomlWithActions))),
        })

        render(<EnvironmentsSection readFileBridge={{ ReadFile: mockReadFile }} />)

        fireEvent.click(screen.getByText('EasyCLIProxyAPI'))

        // Verify actions rendered
        await screen.findByText('Run')
        expect(screen.getByText('npm run dev')).toBeInTheDocument()
        expect(screen.getByText('Build Tool')).toBeInTheDocument()
        expect(screen.getByText('npm run build')).toBeInTheDocument()
        expect(screen.getByText('Debug App')).toBeInTheDocument()
        expect(screen.getByText('npm run debug')).toBeInTheDocument()
        expect(screen.getByText('Start Server')).toBeInTheDocument()
        expect(screen.getByText('npm start')).toBeInTheDocument()
    })

    it('handles action platform selection and saves platform appropriately', async () => {
        const tomlWithDarwinAction = `# THIS IS AUTOGENERATED. DO NOT EDIT MANUALLY
version = 1
name = "EasyCLIProxyAPI"

[[actions]]
name = "Run"
icon = "debug"
command = "npm run dev"
platform = "darwin"
`
        let savedContent = ''
        const mockReadFile = vi.fn().mockImplementation(async (filePath: string) => {
            if (filePath.includes('.codex/environments/environment.toml')) {
                return {
                    dataBase64: btoa(unescape(encodeURIComponent(tomlWithDarwinAction))),
                }
            }
            throw new Error('Not found')
        })
        const mockWriteFile = vi.fn().mockImplementation(async (_path: string, dataBase64: string) => {
            savedContent = decodeURIComponent(escape(atob(dataBase64)))
        })

        render(
            <EnvironmentsSection
                readFileBridge={{ ReadFile: mockReadFile }}
                writeFileBridge={{
                    ReadFile: mockReadFile,
                    WriteFile: mockWriteFile,
                    MkdirAll: vi.fn().mockResolvedValue(undefined),
                }}
            />
        )

        fireEvent.click(screen.getByText('EasyCLIProxyAPI'))
        await screen.findByRole('heading', { level: 1, name: 'EasyCLIProxyAPI' })

        // Detail view shows action name and macOS badge
        expect(screen.getByText('Run')).toBeInTheDocument()
        expect(screen.getAllByText('macOS').length).toBeGreaterThanOrEqual(3)

        // Open edit view
        fireEvent.click(screen.getByRole('button', { name: 'Edit' }))
        expect(
            screen.getByRole('heading', { level: 1, name: 'Edit local environment' })
        ).toBeInTheDocument()

        // macOS button for action should be selected (styled with bg-[var(--bg-sidebar-hover)])
        const allPlatformsBtn = screen.getByRole('button', { name: 'All platforms' })
        const macosBtns = screen.getAllByRole('button', { name: 'macOS' })
        const actionMacosBtn = macosBtns[macosBtns.length - 1]!
        const windowsBtns = screen.getAllByRole('button', { name: 'Windows' })
        const actionWindowsBtn = windowsBtns[windowsBtns.length - 1]!

        expect(actionMacosBtn.className).toContain('bg-[var(--bg-sidebar-hover)]')
        expect(allPlatformsBtn.className).not.toContain('bg-[var(--bg-sidebar-hover)]')

        // Switch to Windows (win32)
        fireEvent.click(actionWindowsBtn)
        expect(actionWindowsBtn.className).toContain('bg-[var(--bg-sidebar-hover)]')
        expect(actionMacosBtn.className).not.toContain('bg-[var(--bg-sidebar-hover)]')

        // Save and verify saved toml has platform = "win32"
        fireEvent.click(screen.getByRole('button', { name: 'Save' }))
        await vi.waitFor(() => expect(savedContent).toContain('platform = "win32"'))

        // Edit again and switch to "All platforms" (all platforms)
        fireEvent.click(screen.getByRole('button', { name: 'Edit' }))
        const allPlatformsBtn2 = screen.getByRole('button', { name: 'All platforms' })
        fireEvent.click(allPlatformsBtn2)

        // Save and verify saved toml does NOT have platform key
        fireEvent.click(screen.getByRole('button', { name: 'Save' }))
        await vi.waitFor(() => expect(savedContent).not.toContain('platform ='))
    })

    it('opens icon menu and allows selecting action icons', async () => {
        const tomlWithAction = `# THIS IS AUTOGENERATED. DO NOT EDIT MANUALLY
version = 1
name = "EasyCLIProxyAPI"

[[actions]]
name = "Run"
icon = "debug"
command = "npm run dev"
`
        let savedContent = ''
        const mockReadFile = vi.fn().mockImplementation(async (filePath: string) => {
            if (filePath.includes('.codex/environments/environment.toml')) {
                return {
                    dataBase64: btoa(unescape(encodeURIComponent(tomlWithAction))),
                }
            }
            throw new Error('Not found')
        })
        const mockWriteFile = vi.fn().mockImplementation(async (_path: string, dataBase64: string) => {
            savedContent = decodeURIComponent(escape(atob(dataBase64)))
        })

        render(
            <EnvironmentsSection
                readFileBridge={{ ReadFile: mockReadFile }}
                writeFileBridge={{
                    ReadFile: mockReadFile,
                    WriteFile: mockWriteFile,
                    MkdirAll: vi.fn().mockResolvedValue(undefined),
                }}
            />
        )

        fireEvent.click(screen.getByText('EasyCLIProxyAPI'))
        await screen.findByRole('heading', { level: 1, name: 'EasyCLIProxyAPI' })

        // Open edit view
        fireEvent.click(screen.getByRole('button', { name: 'Edit' }))
        expect(
            screen.getByRole('heading', { level: 1, name: 'Edit local environment' })
        ).toBeInTheDocument()

        const iconBtn = screen.getByRole('button', { name: 'Action icon: debug' })
        expect(iconBtn).toBeInTheDocument()

        // Click icon button to open dropdown menu
        fireEvent.click(iconBtn)

        // Menu should display all 4 icon options: Tool, Run, Debug, Test
        const menu = screen.getByRole('menu', { name: 'Select icon' })
        expect(menu).toBeInTheDocument()

        expect(screen.getByRole('menuitem', { name: 'Tool' })).toBeInTheDocument()
        expect(screen.getByRole('menuitem', { name: 'Run' })).toBeInTheDocument()
        expect(screen.getByRole('menuitem', { name: 'Debug' })).toBeInTheDocument()
        expect(screen.getByRole('menuitem', { name: 'Test' })).toBeInTheDocument()

        // Select 'Tool' (tool)
        fireEvent.click(screen.getByRole('menuitem', { name: 'Tool' }))

        // Menu should close
        expect(screen.queryByRole('menu', { name: 'Select icon' })).not.toBeInTheDocument()

        // Icon button should now have label for tool
        expect(screen.getByRole('button', { name: 'Action icon: tool' })).toBeInTheDocument()

        // Save and verify saved toml has icon = "tool"
        fireEvent.click(screen.getByRole('button', { name: 'Save' }))
        await vi.waitFor(() => expect(savedContent).toContain('icon = "tool"'))
    })

    it('shows only "Back" button in breadcrumb when navigated from chat', async () => {
        useUiStore.setState({
            settingsOpen: true,
            settingsSection: 'environments',
            settingsParams: { projectId: 'proj-1', mode: 'edit', fromChat: true },
        })

        const sampleToml = `version = 1\nname = "EasyCLIProxyAPI"`
        const mockReadFile = vi.fn().mockImplementation(async (filePath: string) => {
            if (filePath.includes('/workspaces/EasyCLIProxyAPI/')) {
                return { dataBase64: btoa(sampleToml) }
            }
            throw new Error('Not found')
        })

        render(<EnvironmentsSection readFileBridge={{ ReadFile: mockReadFile }} />)

        const breadcrumbNav = screen.getByRole('navigation', { name: 'Breadcrumb' })
        const backBtn = await screen.findByRole('button', { name: 'Back' })
        expect(backBtn).toBeInTheDocument()
        expect(breadcrumbNav).toContainElement(backBtn)

        // Does NOT render the rest of the breadcrumb trail inside breadcrumb nav
        expect(breadcrumbNav).not.toHaveTextContent('EasyCLIProxyAPI')
        expect(breadcrumbNav).not.toHaveTextContent('Environments')

        fireEvent.click(backBtn)
        expect(useUiStore.getState().settingsOpen).toBe(false)
    })

    it('shows full breadcrumb when navigating within settings normally', async () => {
        useUiStore.setState({
            settingsOpen: true,
            settingsSection: 'environments',
            settingsParams: undefined,
        })

        render(<EnvironmentsSection />)

        // Select project
        fireEvent.click(screen.getByText('EasyCLIProxyAPI'))

        const breadcrumbNav = screen.getByRole('navigation', { name: 'Breadcrumb' })
        expect(breadcrumbNav).toHaveTextContent('Environments')
        expect(breadcrumbNav).toHaveTextContent('EasyCLIProxyAPI')

        // Go to edit mode
        fireEvent.click(screen.getByRole('button', { name: 'Create local environment' }))
        const editBreadcrumbNav = screen.getByRole('navigation', { name: 'Breadcrumb' })
        expect(editBreadcrumbNav).toHaveTextContent('Environments')
        expect(editBreadcrumbNav).toHaveTextContent('EasyCLIProxyAPI')
        expect(editBreadcrumbNav).toHaveTextContent('Edit')
    })

    it('does not reset selected platform tab to default when store projects update after navigating from chat in edit mode', async () => {
        useUiStore.setState({
            settingsOpen: true,
            settingsSection: 'environments',
            settingsParams: { projectId: 'proj-1', mode: 'edit', fromChat: true },
        })

        const sampleToml = `version = 1\nname = "EasyCLIProxyAPI"\n[setup]\nscript = "npm start"\n[setup.darwin]\nscript = "npm run start:macos"`
        const mockReadFile = vi.fn().mockImplementation(async (filePath: string) => {
            if (filePath.includes('/workspaces/EasyCLIProxyAPI/')) {
                return { dataBase64: btoa(sampleToml) }
            }
            throw new Error('Not found')
        })

        render(<EnvironmentsSection readFileBridge={{ ReadFile: mockReadFile }} />)

        // Wait for edit view to be ready
        await screen.findByRole('heading', { level: 1, name: 'Edit local environment' })

        // Click macOS tab for setup script
        const macosBtns = screen.getAllByRole('button', { name: 'macOS' })
        fireEvent.click(macosBtns[0]!)

        const setupTextarea = screen.getByLabelText('Setup script') as HTMLTextAreaElement
        expect(setupTextarea.value).toBe('npm run start:macos')

        // Edit text
        fireEvent.change(setupTextarea, { target: { value: 'npm run custom:macos' } })
        expect(setupTextarea.value).toBe('npm run custom:macos')

        // Simulate background projectStore update (e.g. status probe, persist, or auto-save)
        useProjectStore.setState({
            projects: MOCK_PROJECTS.map((p) =>
                p.id === 'proj-1' ? { ...p, updatedAt: Date.now() + 1000 } : { ...p }
            ),
        })

        // Verify that macOS tab is still active and edited value is preserved
        const setupMacosBtn = screen.getAllByRole('button', { name: 'macOS' })[0]!
        expect(setupMacosBtn.className).toContain('bg-[var(--bg-sidebar-hover)]')
        expect(setupTextarea.value).toBe('npm run custom:macos')
    })

    it('does not reset selected platform tab to default when store projects update after navigating from chat in detail mode', async () => {
        useUiStore.setState({
            settingsOpen: true,
            settingsSection: 'environments',
            settingsParams: { projectId: 'proj-1', mode: 'detail', fromChat: true },
        })

        const sampleToml = `version = 1\nname = "EasyCLIProxyAPI"\n[setup]\nscript = "echo default-setup"\n[setup.darwin]\nscript = "echo macos-setup"`
        const mockReadFile = vi.fn().mockImplementation(async (filePath: string) => {
            if (filePath.includes('/workspaces/EasyCLIProxyAPI/')) {
                return { dataBase64: btoa(sampleToml) }
            }
            throw new Error('Not found')
        })

        render(<EnvironmentsSection readFileBridge={{ ReadFile: mockReadFile }} />)

        // Wait for detail view
        await screen.findByRole('heading', { level: 1, name: 'EasyCLIProxyAPI' })
        expect(screen.getByText('default-setup')).toBeInTheDocument()

        // Click macOS tab for setup script
        const macosBtns = screen.getAllByRole('button', { name: 'macOS' })
        fireEvent.click(macosBtns[0]!)
        expect(screen.getByText('macos-setup')).toBeInTheDocument()

        // Simulate background store update
        useProjectStore.setState({
            projects: [...MOCK_PROJECTS],
        })

        // Verify that macOS tab is still selected and shows macOS script
        const setupMacosBtn = screen.getAllByRole('button', { name: 'macOS' })[0]!
        expect(setupMacosBtn.className).toContain('bg-[var(--bg-sidebar-hover)]')
        expect(screen.getByText('macos-setup')).toBeInTheDocument()
    })
})
