import { describe, expect, it, vi } from 'vitest'
import {
    invalidateProjectEnvironmentCache,
    normalizeActionPlatform,
    normalizePlatformKey,
    parseEnvironmentToml,
    readProjectEnvironment,
    saveProjectEnvironment,
    serializeEnvironmentToml,
    toTomlPlatformKey,
} from './environmentToml'
import { setHostBridge } from '@/application/services/hostTransport'

const SAMPLE_TOML = `# THIS IS AUTOGENERATED. DO NOT EDIT MANUALLY
version = 1
name = "EasyCLIProxyAPI"

[setup]
script = "cd \\"$CODEX_SOURCE_TREE_PATH\\""

[setup.darwin]
script = "cd \\"$CODEX_SOURCE_TREE_PATH-macos\\""

[setup.linux]
script = "cd \\"$CODEX_SOURCE_TREE_PATH-linux\\""

[setup.win32]
script = "cd \\"$CODEX_SOURCE_TREE_PATH-windows\\""

[cleanup]
script = "cd \\"$CODEX_WORKTREE_PATH\\""

[cleanup.darwin]
script = "cd \\"$CODEX_WORKTREE_PATH-macos\\""

[cleanup.linux]
script = "cd \\"$CODEX_WORKTREE_PATH-linux\\""

[cleanup.win32]
script = "cd \\"$CODEX_WORKTREE_PATH-windows\\""
`

const ACTIONS_TOML = `# THIS IS AUTOGENERATED. DO NOT EDIT MANUALLY
version = 1
name = "codex"

[setup]
script = ""

[[actions]]
name = "Run"
icon = "run"
command = "cargo +1.95.0 run --manifest-path=codex-rs/Cargo.toml --bin codex"
`

describe('environmentToml', () => {
    describe('normalizePlatformKey & toTomlPlatformKey', () => {
        it('normalizes platform keys correctly', () => {
            expect(normalizePlatformKey('darwin')).toBe('macos')
            expect(normalizePlatformKey('macos')).toBe('macos')
            expect(normalizePlatformKey('linux')).toBe('linux')
            expect(normalizePlatformKey('win32')).toBe('windows')
            expect(normalizePlatformKey('windows')).toBe('windows')
            expect(normalizePlatformKey('other')).toBe('default')
        })

        it('converts to TOML platform keys correctly', () => {
            expect(toTomlPlatformKey('macos')).toBe('darwin')
            expect(toTomlPlatformKey('windows')).toBe('win32')
            expect(toTomlPlatformKey('linux')).toBe('linux')
            expect(toTomlPlatformKey('default')).toBe('default')
        })
    })

    describe('normalizeActionPlatform', () => {
        it('normalizes action platform keys correctly', () => {
            expect(normalizeActionPlatform('darwin')).toBe('darwin')
            expect(normalizeActionPlatform('macos')).toBe('darwin')
            expect(normalizeActionPlatform('mac')).toBe('darwin')
            expect(normalizeActionPlatform('linux')).toBe('linux')
            expect(normalizeActionPlatform('win32')).toBe('win32')
            expect(normalizeActionPlatform('windows')).toBe('win32')
            expect(normalizeActionPlatform('win')).toBe('win32')
            expect(normalizeActionPlatform('all')).toBeUndefined()
            expect(normalizeActionPlatform(undefined)).toBeUndefined()
            expect(normalizeActionPlatform('')).toBeUndefined()
        })
    })

    describe('parseEnvironmentToml', () => {
        it('parses the sample EasyCLIProxyAPI environment.toml', () => {
            const config = parseEnvironmentToml(SAMPLE_TOML)

            expect(config.version).toBe(1)
            expect(config.name).toBe('EasyCLIProxyAPI')

            expect(config.setupScripts?.default).toBe('cd "$CODEX_SOURCE_TREE_PATH"')
            expect(config.setupScripts?.macos).toBe('cd "$CODEX_SOURCE_TREE_PATH-macos"')
            expect(config.setupScripts?.linux).toBe('cd "$CODEX_SOURCE_TREE_PATH-linux"')
            expect(config.setupScripts?.windows).toBe('cd "$CODEX_SOURCE_TREE_PATH-windows"')

            expect(config.cleanupScripts?.default).toBe('cd "$CODEX_WORKTREE_PATH"')
            expect(config.cleanupScripts?.macos).toBe('cd "$CODEX_WORKTREE_PATH-macos"')
            expect(config.cleanupScripts?.linux).toBe('cd "$CODEX_WORKTREE_PATH-linux"')
            expect(config.cleanupScripts?.windows).toBe('cd "$CODEX_WORKTREE_PATH-windows"')
        })

        it('parses actions correctly from toml', () => {
            const config = parseEnvironmentToml(ACTIONS_TOML)

            expect(config.version).toBe(1)
            expect(config.name).toBe('codex')
            expect(config.setupScripts?.default).toBe('')
            expect(config.actions).toHaveLength(1)
            expect(config.actions?.[0]?.name).toBe('Run')
            expect(config.actions?.[0]?.icon).toBe('run')
            expect(config.actions?.[0]?.script).toBe(
                'cargo +1.95.0 run --manifest-path=codex-rs/Cargo.toml --bin codex'
            )
        })

        it('parses actions with platform correctly from toml', () => {
            const toml = `# THIS IS AUTOGENERATED. DO NOT EDIT MANUALLY
version = 1
name = "EasyCLIProxyAPI"

[[actions]]
name = "Run"
icon = "debug"
command = "npm run dev"
platform = "darwin"

[[actions]]
name = "Build Linux"
command = "npm run build"
platform = "linux"

[[actions]]
name = "All Platforms Action"
command = "npm test"
`
            const config = parseEnvironmentToml(toml)
            expect(config.actions).toHaveLength(3)
            expect(config.actions?.[0]?.name).toBe('Run')
            expect(config.actions?.[0]?.platform).toBe('darwin')
            expect(config.actions?.[0]?.icon).toBe('debug')
            expect(config.actions?.[1]?.name).toBe('Build Linux')
            expect(config.actions?.[1]?.platform).toBe('linux')
            expect(config.actions?.[2]?.name).toBe('All Platforms Action')
            expect(config.actions?.[2]?.platform).toBeUndefined()
        })
    })

    describe('serializeEnvironmentToml', () => {
        it('serializes config round-trip', () => {
            const parsed = parseEnvironmentToml(SAMPLE_TOML)
            const serialized = serializeEnvironmentToml(parsed)
            const reParsed = parseEnvironmentToml(serialized)

            expect(reParsed.name).toBe(parsed.name)
            expect(reParsed.setupScripts).toEqual(parsed.setupScripts)
            expect(reParsed.cleanupScripts).toEqual(parsed.cleanupScripts)
        })

        it('serializes actions with platform and removes platform for all platforms', () => {
            const serialized = serializeEnvironmentToml({
                version: 1,
                name: 'EasyCLIProxyAPI',
                actions: [
                    {
                        id: '1',
                        name: 'Run',
                        script: 'npm run dev',
                        icon: 'debug',
                        platform: 'darwin',
                    },
                    {
                        id: '2',
                        name: 'General',
                        script: 'npm test',
                        // all platforms - no platform field
                    },
                ],
            })

            expect(serialized).toContain('[[actions]]\nname = "Run"\nicon = "debug"\ncommand = "npm run dev"\nplatform = "darwin"')
            expect(serialized).toContain('[[actions]]\nname = "General"\ncommand = "npm test"')
            expect(serialized).not.toContain('name = "General"\ncommand = "npm test"\nplatform =')
        })
    })

    describe('readProjectEnvironment', () => {
        it('reads .cpa path if present', async () => {
            const mockReadFile = vi.fn().mockImplementation(async (filePath: string) => {
                if (filePath.includes('.cpa')) {
                    const base64 = btoa(SAMPLE_TOML)
                    return { dataBase64: base64 }
                }
                throw new Error('Not found')
            })

            const result = await readProjectEnvironment('/test/project', {
                ReadFile: mockReadFile,
            })

            expect(result).not.toBeNull()
            expect(result?.config.name).toBe('EasyCLIProxyAPI')
            expect(result?.filePath).toBe('/test/project/.cpa/environments/environment.toml')
        })

        it('falls back to .codex path if .cpa is not present', async () => {
            const mockReadFile = vi.fn().mockImplementation(async (filePath: string) => {
                if (filePath.includes('.codex')) {
                    const base64 = btoa(SAMPLE_TOML)
                    return { dataBase64: base64 }
                }
                throw new Error('Not found')
            })

            const result = await readProjectEnvironment('/test/project', {
                ReadFile: mockReadFile,
            })

            expect(result).not.toBeNull()
            expect(result?.config.name).toBe('EasyCLIProxyAPI')
            expect(result?.filePath).toBe('/test/project/.codex/environments/environment.toml')
        })

        it('falls back to root environment.toml if neither .cpa nor .codex is present', async () => {
            const mockReadFile = vi.fn().mockImplementation(async (filePath: string) => {
                if (filePath === '/test/project/environment.toml') {
                    const base64 = btoa(SAMPLE_TOML)
                    return { dataBase64: base64 }
                }
                throw new Error('Not found')
            })

            const result = await readProjectEnvironment('/test/project', {
                ReadFile: mockReadFile,
            })

            expect(result).not.toBeNull()
            expect(result?.config.name).toBe('EasyCLIProxyAPI')
            expect(result?.filePath).toBe('/test/project/environment.toml')
        })

        it('returns null if neither file is present', async () => {
            const mockReadFile = vi.fn().mockRejectedValue(new Error('ENOENT'))

            const result = await readProjectEnvironment('/test/project', {
                ReadFile: mockReadFile,
            })

            expect(result).toBeNull()
        })

        it('supports GetProjectEnvironment when provided on bridge', async () => {
            const mockGetProjectEnvironment = vi.fn().mockResolvedValue({
                filePath: '/test/custom/.cpa/environments/environment.toml',
                content: 'name = "FromRpc"\n',
            })

            const result = await readProjectEnvironment('/test/custom', {
                ReadFile: vi.fn(),
                GetProjectEnvironment: mockGetProjectEnvironment,
            })

            expect(result).not.toBeNull()
            expect(result?.config.name).toBe('FromRpc')
            expect(result?.filePath).toBe('/test/custom/.cpa/environments/environment.toml')
        })

        it('supports ReadFileIfExists when provided on bridge without throwing', async () => {
            const mockReadFileIfExists = vi.fn().mockImplementation(async (filePath: string) => {
                if (filePath.includes('.cpa')) {
                    return { dataBase64: btoa('name = "FromSafeRead"\n') }
                }
                return null
            })

            const result = await readProjectEnvironment('/test/safe', {
                ReadFile: vi.fn(),
                ReadFileIfExists: mockReadFileIfExists,
            })

            expect(result).not.toBeNull()
            expect(result?.config.name).toBe('FromSafeRead')
        })

        it('caches results and invalidates properly', async () => {
            invalidateProjectEnvironmentCache()
            const mockReadFile = vi.fn().mockResolvedValue({ dataBase64: btoa('name = "Cached"\n') })

            setHostBridge({
                ReadFile: mockReadFile,
            } as any)

            try {
                const res1 = await readProjectEnvironment('/test/cache-proj')
                expect(res1?.config.name).toBe('Cached')
                expect(mockReadFile).toHaveBeenCalledTimes(1)

                // Second call should return cached without calling ReadFile again
                const res2 = await readProjectEnvironment('/test/cache-proj')
                expect(res2?.config.name).toBe('Cached')
                expect(mockReadFile).toHaveBeenCalledTimes(1)

                // After invalidation, should call again
                invalidateProjectEnvironmentCache('/test/cache-proj')
                const res3 = await readProjectEnvironment('/test/cache-proj')
                expect(res3?.config.name).toBe('Cached')
                expect(mockReadFile).toHaveBeenCalledTimes(2)
            } finally {
                setHostBridge(null)
                invalidateProjectEnvironmentCache()
            }
        })
    })

    describe('saveProjectEnvironment', () => {
        it('writes to .cpa file by default', async () => {
            const mockWriteFile = vi.fn().mockResolvedValue(undefined)
            const mockMkdirAll = vi.fn().mockResolvedValue(undefined)

            const savedPath = await saveProjectEnvironment(
                '/test/project',
                {
                    name: 'TestProject',
                    setupScripts: { default: 'echo setup' },
                },
                undefined,
                {
                    ReadFile: vi.fn(),
                    WriteFile: mockWriteFile,
                    MkdirAll: mockMkdirAll,
                }
            )

            expect(savedPath).toBe('/test/project/.cpa/environments/environment.toml')
            expect(mockMkdirAll).toHaveBeenCalledWith('/test/project/.cpa/environments')
            expect(mockWriteFile).toHaveBeenCalled()
        })
    })
})
